[project]
name = "preprocessing"
version = "1.0.0"
requires-python = ">=3.8,<3.13"
description = "Preprocessing helpers for HYMN-dataset"
dependencies = [
    "xarray>=2024.6.0",
    "pandas>=2.0.0",
    "numpy>=2.0.0"
]