[project]
name = "data-preprocessing"
version = "1.0.0"
requires-python = ">=3.8,<=3.12"
description = "Preprocessing helpers"
dependencies = [
   "numpy >=1.24",
  "xarray>=2024.6.0",
    "pandas>=2.0.0",
]